/**
 * Dynamically generated robots.txt using the configured site URL (e.g. SITE env).
 * Sitemap URL points to the sitemap generated by @astrojs/sitemap.
 */
import type { APIRoute } from "astro";

export const prerender = true;

export const GET: APIRoute = ({ site }) => {
  const sitemapURL = site ? new URL("sitemap-index.xml", site).href : "";
  const body =
    "User-agent: *\nAllow: /\n" + (sitemapURL ? `\nSitemap: ${sitemapURL}\n` : "");
  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
};
